item {
    id: 1
    name: 'Barrel'
}

item {
    id: 2
    name: 'Bicycle'
}

item {
    id: 3
    name: 'Bus'
}

item {
    id: 4
    name: 'Car'
}

item {
    id: 5
    name: 'Chair'
}

item {
    id: 6
    name: 'Dog'
}

item {
    id: 7
    name: 'Fire hydrant'
}

item {
    id: 8
    name: 'Horse'
}

item {
    id: 9
    name: 'Palm tree'
}

item {
    id: 10
    name: 'Person'
}

item {
    id: 11
    name: 'Sculpture'
}

item {
    id: 12
    name: 'Street light'
}

item {
    id: 13
    name: 'Table'
}

item {
    id: 14
    name: 'Traffic light'
}

item {
    id: 15
    name: 'Traffic sign'
}

item {
    id: 16
    name: 'Tree'
}

item {
    id: 17
    name: 'Pozo'
}

item {
    id: 18
    name: 'Baliza'
}

item {
    id: 19
    name: 'Cono'
}